In [18]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
import ast

In [4]:
cymbalair_policy = pd.read_csv("./cymbalair_policy.csv")
airport_dataset = pd.read_csv("./airport_dataset.csv")
flights_dataset = pd.read_csv("./flights_dataset.csv")
amenity_dataset = pd.read_csv("./amenity_dataset.csv")

In [5]:
cymbalair_policy.head(2)

,id,content,embedding
0,0,# Cymbal Air: Passenger Policy \n## Ticket Pu...,"[-0.021210914477705956, -0.0011509297182783484..."
1,1,Changes: Changes to tickets are permitted at a...,"[-0.023659581318497658, 0.0008153968374244869,..."

In [6]:
airport_dataset.head(2)

   id iata            name    city           country
0   0  GKA  Goroka Airport  Goroka  Papua New Guinea
1   1  MAG  Madang Airport  Madang  Papua New Guinea

In [7]:
flights_dataset.head(2)

,id,airline,flight_number,departure_airport,arrival_airport,departure_time,arrival_time,departure_gate,arrival_gate
0,0,UA,1532,SFO,DEN,2025-01-01 05:50:00,2025-01-01 09:23:00,E49,D6
1,1,UA,1158,SFO,ORD,2025-01-01 05:57:00,2025-01-01 12:13:00,C38,D30

In [8]:
amenity_dataset.head(2)

,id,name,description,location,terminal,category,hour,sunday_start_hour,sunday_end_hour,monday_start_hour,...,wednesday_start_hour,wednesday_end_hour,thursday_start_hour,thursday_end_hour,friday_start_hour,friday_end_hour,saturday_start_hour,saturday_end_hour,content,embedding
0,0,Coffee Shop 732,Serving American cuisine.,Near Gate B12,Terminal 3,restaurant,Daily 7:00 am - 10:00 pm,07:00:00,22:00:00,07:00:00,...,07:00:00,22:00:00,07:00:00,22:00:00,07:00:00,22:00:00,07:00:00,22:00:00,Coffee Shop 732 is a restaurant. Serving Ameri...,"[-0.013121306896209717, 0.005038619972765446, ..."
1,1,Electronics Store 145,Selling electronics.,Near Gate B10,Terminal 2,shop,Daily 9:00 am - 7:00 pm,09:00:00,19:00:00,09:00:00,...,09:00:00,19:00:00,09:00:00,19:00:00,09:00:00,19:00:00,09:00:00,19:00:00,Electronics Store 145 is a shop. Selling elect...,"[-0.009227288886904716, -0.01255660131573677, ..."

In [9]:
amenity_dataset.columns

Index(['id', 'name', 'description', 'location', 'terminal', 'category', 'hour',
       'sunday_start_hour', 'sunday_end_hour', 'monday_start_hour',
       'monday_end_hour', 'tuesday_start_hour', 'tuesday_end_hour',
       'wednesday_start_hour', 'wednesday_end_hour', 'thursday_start_hour',
       'thursday_end_hour', 'friday_start_hour', 'friday_end_hour',
       'saturday_start_hour', 'saturday_end_hour', 'content', 'embedding'],
      dtype='str')

In [10]:
embedding = cymbalair_policy.iloc[0]['embedding']

In [34]:
len(ast.literal_eval(embedding))

3072

In [12]:
amenity_embedding = amenity_dataset.iloc[0]['embedding']

In [35]:
len(ast.literal_eval(amenity_embedding))

3072